// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game_data.proto
#ifndef GRPC_game_5fdata_2eproto__INCLUDED
#define GRPC_game_5fdata_2eproto__INCLUDED

#include "game_data.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace rlbot {
namespace api {

class Bot final {
 public:
  static constexpr char const* service_full_name() {
    return "rlbot.api.Bot";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::rlbot::api::ControllerState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>> AsyncGetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>>(AsyncGetControllerStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>> PrepareAsyncGetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>>(PrepareAsyncGetControllerStateRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>* AsyncGetControllerStateRaw(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rlbot::api::ControllerState>* PrepareAsyncGetControllerStateRaw(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::rlbot::api::ControllerState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>> AsyncGetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>>(AsyncGetControllerStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>> PrepareAsyncGetControllerState(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>>(PrepareAsyncGetControllerStateRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>* AsyncGetControllerStateRaw(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rlbot::api::ControllerState>* PrepareAsyncGetControllerStateRaw(::grpc::ClientContext* context, const ::rlbot::api::GameTickPacket& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetControllerState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetControllerState(::grpc::ServerContext* context, const ::rlbot::api::GameTickPacket* request, ::rlbot::api::ControllerState* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetControllerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetControllerState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetControllerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControllerState(::grpc::ServerContext* context, const ::rlbot::api::GameTickPacket* request, ::rlbot::api::ControllerState* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetControllerState(::grpc::ServerContext* context, ::rlbot::api::GameTickPacket* request, ::grpc::ServerAsyncResponseWriter< ::rlbot::api::ControllerState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetControllerState<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetControllerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetControllerState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetControllerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetControllerState(::grpc::ServerContext* context, const ::rlbot::api::GameTickPacket* request, ::rlbot::api::ControllerState* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetControllerState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetControllerState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::rlbot::api::GameTickPacket, ::rlbot::api::ControllerState>(std::bind(&WithStreamedUnaryMethod_GetControllerState<BaseClass>::StreamedGetControllerState, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetControllerState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetControllerState(::grpc::ServerContext* context, const ::rlbot::api::GameTickPacket* request, ::rlbot::api::ControllerState* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetControllerState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rlbot::api::GameTickPacket,::rlbot::api::ControllerState>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetControllerState<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetControllerState<Service > StreamedService;
};

}  // namespace api
}  // namespace rlbot


#endif  // GRPC_game_5fdata_2eproto__INCLUDED
